FROM resin/%%RESIN_MACHINE_NAME%%-debian:latest

WORKDIR /usr/src/app
ENV INITSYSTEM on

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
      parprouted dhcp-helper avahi-daemon

COPY conf/dhcp-helper /etc/default/dhcp-helper
COPY conf/avahi-daemon.conf /etc/avahi/avahi-daemon.conf
COPY start.sh ./

CMD ["bash", "start.sh"]
